/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#f8f9ff",
        "surface-dim": "#d0dbed",
        "surface-bright": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e6eeff",
        "surface-container-high": "#dee9fc",
        "surface-container-highest": "#d9e3f6",
        "on-surface": "#121c2a",
        "on-surface-variant": "#3f4944",
        "inverse-surface": "#27313f",
        "inverse-on-surface": "#eaf1ff",
        "surface-tint": "#1b6b51",
        primary: "#004532",
        "on-primary": "#ffffff",
        "primary-container": "#065f46",
        "on-primary-container": "#8bd6b7",
        "inverse-primary": "#8bd6b6",
        secondary: "#416656",
        "on-secondary": "#ffffff",
        "secondary-container": "#c3ecd7",
        "on-secondary-container": "#476c5b",
        tertiary: "#353c4c",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#4c5364",
        "on-tertiary-container": "#c0c7dc",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#a6f2d1",
        "primary-fixed-dim": "#8bd6b6",
        "on-primary-fixed": "#002116",
        "on-primary-fixed-variant": "#00513b",
        "secondary-fixed": "#c3ecd7",
        "secondary-fixed-dim": "#a8cfbc",
        "on-secondary-fixed": "#002115",
        "on-secondary-fixed-variant": "#294e3f",
        "tertiary-fixed": "#dce2f7",
        "tertiary-fixed-dim": "#c0c6db",
        "on-tertiary-fixed": "#141b2b",
        "on-tertiary-fixed-variant": "#404758",
        background: "#f8f9ff",
        "on-background": "#121c2a",
        "surface-variant": "#d9e3f6",
        outline: "#6f7973",
        "outline-variant": "#bec9c2",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        base: "4px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "48px",
        "container-max": "1280px",
        gutter: "24px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "body-sm": ["Inter"],
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "label-sm": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        display: ["Inter"],
        "label-md": ["Inter"],
      },
      fontSize: {
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        display: ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
